name: Bug
description: Report a problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Remember: Lazyvim

  - type: input
    id: system-details
    attributes:
      label: System details
      placeholder: Lazyvim
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: What's wrong?
    validations:
      required: true
